//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web.API.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nhập vào không hợp lệ.
        /// </summary>
        public static string Error_Code_400 {
            get {
                return ResourceManager.GetString("Error_Code_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày được chọn phải trước ngày hiện tại.
        /// </summary>
        public static string Error_Date {
            get {
                return ResourceManager.GetString("Error_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép trùng.
        /// </summary>
        public static string Error_Duplicate_EmployeeCode {
            get {
                return ResourceManager.GetString("Error_Duplicate_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập email đúng định dạng.
        /// </summary>
        public static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập mã nhân viên.
        /// </summary>
        public static string Error_EmployeeCode {
            get {
                return ResourceManager.GetString("Error_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập tên nhân viên.
        /// </summary>
        public static string Error_EmployeeName {
            get {
                return ResourceManager.GetString("Error_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ Misa để biết thêm thông tin chi tiết!.
        /// </summary>
        public static string Error_Exeption {
            get {
                return ResourceManager.GetString("Error_Exeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập số điện thoại.
        /// </summary>
        public static string Error_PhoneNumber {
            get {
                return ResourceManager.GetString("Error_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu thành công.
        /// </summary>
        public static string Success_Add {
            get {
                return ResourceManager.GetString("Success_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thành công.
        /// </summary>
        public static string Success_Add_Employee {
            get {
                return ResourceManager.GetString("Success_Add_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu thành công.
        /// </summary>
        public static string Success_Update {
            get {
                return ResourceManager.GetString("Success_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa nhân viên thành công.
        /// </summary>
        public static string Success_Update_Employee {
            get {
                return ResourceManager.GetString("Success_Update_Employee", resourceCulture);
            }
        }
    }
}
